org: bolazoo
app: blog-backend-2
service: aws-node-http-api-project
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    DYNAMODB_CUSTOMER_TABLE: ${self:service}-customerTable-${sls:stage}
    CONTENTFUL_ACCESS_TOKEN: ${ssm:/aws/reference/secretsmanager/contentful_access_token}
    CONTENTFUL_SPACE_KEY: ${ssm:/aws/reference/secretsmanager/contentful_space_key}
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:Get*"
            - "dynamodb:Scan*"
            - "dynamodb:UpdateItem"
            - "dynamodb:DeleteItem"
          Resource: arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:service}-customerTable-${sls:stage}

functions:
  createComment:
    handler: app/comments.createComment
    events:
      - httpApi:
          path: /
          method: post
  getCommentsByBlog:
    handler: app/comments.getCommentsByBlog
    events:
      - httpApi:
          path: /
          method: get
  getAllBlogs:
    handler: app/contentful.getAllBlogs
    events:
      - httpApi:
          path: /blog
          method: get
  getSingleBlog:
    handler: app/contentful.getSingleBlog
    events:
      - httpApi:
          path: /blog/{id}
          method: get

resources:
  Resources:
    CustomerTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: primary_key
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: primary_key
            KeyType: HASH
        TableName: ${self:service}-customerTable-${sls:stage}
